# Utiliser l'image Node.js 18 pour construire le frontend
FROM node:18 AS frontend-build
WORKDIR /app/frontend

# Copie des fichiers de package du frontend et les utilises pour installer les dépendances
COPY frontend/package*.json ./
COPY frontend/ .
RUN npm install

# Construire le frontend
RUN npm run build

# Utiliser l'image Node.js 18 pour construire le backend
FROM node:18 AS backend
WORKDIR /app/backend

# Copie des fichiers de package du backend et les utilises pour installer les dépendances
COPY backend/package*.json ./
RUN npm install

# Copier les fichiers source du backend
COPY backend/ .

# Copier les fichiers construits du frontend dans le répertoire dist du backend
COPY --from=frontend-build /app/frontend/dist /app/backend/dist

# Mandodb env variables
ENV DB_URL=mongodb://mongodb:27017/db_to-do
ENV NODE_ENV=production

# Exposer le port 3000
EXPOSE 3000

# Démarrer l'application backend
CMD ["npm", "start"]