version: '3.8'

services:
  mongo:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"


  backend:
    image: mynegret/todo-backend:latest
    container_name: backend
    depends_on:
      - mongo
    ports:
      - "3000:3000"

  frontend:
    image: mynegret/todo-frontend:latest
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "4173:4173"

