name: CI/CD Workflow for Todo App

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Images to Docker Hub
    runs-on: ubuntu-latest
    environment: CI-TEST

    steps:
    # Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # Login to Docker Hub
    - name: Login to Docker Hub
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

    # Build Backend Image
    - name: Build Backend Docker Image
      run: |
        docker build Code/backend -f Code/backend/dockerfile -t ${DOCKERHUB_USERNAME}/todo-backend:latest
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    # Push Backend Image
    - name: Push Backend Docker Image
      run: |
        docker push ${DOCKERHUB_USERNAME}/todo-backend:latest
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    # Build Frontend Image
    - name: Build Frontend Docker Image
      run: |
        docker build Code/frontend -f Code/frontend/dockerfile -t ${DOCKERHUB_USERNAME}/todo-frontend:latest
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    # Push Frontend Image
    - name: Push Frontend Docker Image
      run: |
        docker push ${DOCKERHUB_USERNAME}/todo-frontend:latest
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

  validate-deployment:
    name: Validate Deployment
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    # Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v4

    # Install docker-compose
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    # Deploy App Locally
    - name: Start Services with Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d

    # Test Backend Endpoint
    - name: Test Backend Service
      run: |
        curl -f http://localhost:3000/api/health || exit 1

    # Test Frontend Endpoint
    - name: Test Frontend Service
      run: |
        curl -f http://localhost:4173 || exit 1

    # Stop Services
    - name: Stop Docker Compose Services
      if: always()
      run: |
        docker-compose -f docker-compose.yml down
